name: Run Selenium Tests

on:
  push:
    branches:
      - main  # или master, в зависимости от вашей ветки
  pull_request:
    branches:
      - main  # или master

jobs:
  selenium_tests:
    runs-on: ubuntu-latest  # Используем Ubuntu для CI

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: --shm-size=2g  # Увеличиваем размер shared memory, чтобы избежать ошибок с браузером

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Действие для загрузки кода из репозитория

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Указываем версию Python, которая используется в проекте

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  # Устанавливаем все зависимости из requirements.txt

      - name: Run Selenium tests
        run: |
          python -m pytest  # Запуск тестов с помощью pytest
